import { useThemeVars } from '@consta/uikit/useThemeVars';

export const useEChartsTheme = () => {
  const theme = useThemeVars();

  return {
    seriesCnt: '3',
    backgroundColor: theme.color.primary['--color-bg-default'],
    titleColor: theme.color.primary['--color-control-typo-default'],
    subtitleColor: theme.color.primary['--color-bg-border'], // ?
    textColorShow: false,
    textColor: theme.color.primary['--color-typo-primary'],
    markTextColor: theme.color.primary['--color-bg-default'], // ?
    color: [
      theme.color.primary['--color-bg-normal'],
      theme.color.primary['--color-bg-warning'],
      theme.color.primary['--color-bg-success'],
      theme.color.primary['--color-bg-caution'],
      theme.color.primary['--color-bg-alert'],
    ],
    borderColor: theme.color.primary['--color-bg-border'],
    borderWidth: 0,
    visualMapColor: [
      theme.color.primary['--color-bg-normal'],
      theme.color.primary['--color-bg-warning'],
      theme.color.primary['--color-bg-success'],
      theme.color.primary['--color-bg-caution'],
      theme.color.primary['--color-bg-alert'],
    ],
    legendTextColor: theme.color.primary['--color-typo-primary'],
    kColor: theme.color.primary['--color-bg-alert'],
    kColor0: theme.color.primary['--color-bg-success'],
    kBorderColor: theme.color.primary['--color-bg-alert'],
    kBorderColor0: theme.color.primary['--color-bg-success'],
    kBorderWidth: '1',
    lineWidth: '3',
    symbolSize: '8',
    symbol: 'circle',
    symbolBorderWidth: '0',
    lineSmooth: false,
    graphLineWidth: '1',
    graphLineColor: theme.color.primary['--color-bg-border'],
    mapLabelColor: '#28544e',
    mapLabelColorE: '#349e8e',
    mapBorderColor: '#999999',
    mapBorderColorE: '#22c3aa',
    mapBorderWidth: 0.5,
    mapBorderWidthE: 1,
    mapAreaColor: '#eeeeee',
    mapAreaColorE: 'rgba(34,195,170,0.25)',
    axes: [
      {
        type: 'all',
        name: '通用坐标轴',
        axisLineShow: true,
        axisLineColor: theme.color.primary['--color-bg-border'],
        axisTickShow: true,
        axisTickColor: theme.color.primary['--color-bg-border'],
        axisLabelShow: true,
        axisLabelColor: 'rgba(0,32,51,0.6)',
        splitLineShow: true,
        splitLineColor: [theme.color.primary['--color-bg-border']],
        splitAreaShow: true,
        splitAreaColor: ['rgba(250,250,250,0.05)'],
      },
      {
        type: 'category',
        name: '类目坐标轴',
        axisLineShow: true,
        axisLineColor: '#333',
        axisTickShow: true,
        axisTickColor: '#333',
        axisLabelShow: true,
        axisLabelColor: '#333',
        splitLineShow: false,
        splitLineColor: ['#ccc'],
        splitAreaShow: false,
        splitAreaColor: ['rgba(250,250,250,0.3)', 'rgba(200,200,200,0.3)'],
      },
      {
        type: 'value',
        name: '数值坐标轴',
        axisLineShow: true,
        axisLineColor: '#333',
        axisTickShow: true,
        axisTickColor: '#333',
        axisLabelShow: true,
        axisLabelColor: '#333',
        splitLineShow: true,
        splitLineColor: ['#ccc'],
        splitAreaShow: false,
        splitAreaColor: ['rgba(250,250,250,0.3)', 'rgba(200,200,200,0.3)'],
      },
      {
        type: 'log',
        name: '对数坐标轴',
        axisLineShow: true,
        axisLineColor: '#333',
        axisTickShow: true,
        axisTickColor: '#333',
        axisLabelShow: true,
        axisLabelColor: '#333',
        splitLineShow: true,
        splitLineColor: ['#ccc'],
        splitAreaShow: false,
        splitAreaColor: ['rgba(250,250,250,0.3)', 'rgba(200,200,200,0.3)'],
      },
      {
        type: 'time',
        name: '时间坐标轴',
        axisLineShow: true,
        axisLineColor: '#333',
        axisTickShow: true,
        axisTickColor: '#333',
        axisLabelShow: true,
        axisLabelColor: '#333',
        splitLineShow: true,
        splitLineColor: ['#ccc'],
        splitAreaShow: false,
        splitAreaColor: ['rgba(250,250,250,0.3)', 'rgba(200,200,200,0.3)'],
      },
    ],
    axisSeperateSetting: false,
    toolboxColor: theme.color.primary['--color-bg-link'],
    toolboxEmphasisColor: '#008efa',
    tooltipAxisColor: theme.color.primary['--color-bg-border'],
    tooltipAxisWidth: '1',
    timelineLineColor: theme.color.primary['--color-bg-border'],
    timelineLineWidth: 1,
    timelineItemColor: 'rgba(0,66,105,0.7)', // ?
    timelineItemColorE: 'rgba(0,66,105,0.5)', // ?
    timelineCheckColor: '#ffffff',
    timelineCheckBorderColor: theme.color.primary['--color-bg-link'],
    timelineItemBorderWidth: '0',
    timelineControlColor: theme.color.primary['--color-bg-link'],
    timelineControlBorderColor: theme.color.primary['--color-bg-link'],
    timelineControlBorderWidth: '0',
    timelineLabelColor: theme.color.primary['--color-bg-link'],
    datazoomBackgroundColor: 'rgba(255,255,255,0)',
    datazoomDataColor: 'rgba(222,222,222,1)',
    datazoomFillColor: 'rgba(114,230,212,0.25)',
    datazoomHandleColor: '#cccccc',
    datazoomHandleWidth: '100',
    datazoomLabelColor: '#999999',
  };
};
